### ISSUE TITLE
please tag a release

### ISSUE THREAD

**Issue by soniah** [rocketlaunchr/mysql-go#1]
Thanks for writing this package!

Would you mind tagging this, so it's easier to use with go modules? Something like `git tag v1.0.0` 👍

**Comment by rocketlaunchr-cto** [comment]
done. 
go mods doesn't dictate that a tag be created.By default it will use the latest commit.

**Comment by soniah** [comment]
Thanks!

**Comment by rocketlaunchr-cto** [comment]
@soniah Try `select benchmark(9999999999, md5('when will it end?'));` for an intentionally slow query
