### ISSUE TITLE
Ping and Prepare are not cancellable

### ISSUE THREAD

**Issue by methane** [rocketlaunchr/mysql-go#3]
No need to send kill query for them.

**Comment by pjebs** [comment]
thanks @methane  for discovering this. What adjustments should I do with them? Why did they add ctx to Ping function?

**Comment by methane** [comment]
> What adjustments should I do with them?

Stop sending kill query.

> Why did they add ctx to Ping function?

Because databasel/sql is generic, not specific to MySQL.

BTW, you don't need to provide `Conn.Ping()`.  database/sql doesn't call it.

**Comment by pjebs** [comment]
Are you talking about Conn.PrepareContext and/or Tx.PrepareContext?

**Comment by pjebs** [comment]
Also is there any harm in keeping the context cancelling code as is?

**Comment by methane** [comment]
> Are you talking about Conn.PrepareContext and/or Tx.PrepareContext?

Both.  KILL query is not supported for prepare.


> Also is there any harm in keeping the context cancelling code as is?

It wastes RAM and CPU.  And `go-sql-driver/mysql` supports simple canceling by just closing the connection.  Your implementation bother it.  When the network is unhealthy, your implementation will not return after the context is canceled (including timed out).

**Comment by rocketlaunchr-cto** [comment]
- I have removed cancellation support for Ping and Prepare (Conn/Tx) in `remove-cancel` branch which I will merge to master once I finish testing.

> When the network is unhealthy, your implementation will not return after the context is canceled (including timed out).

Can you explain this part so I can make adjustments for this issue.
What if I add a "overarching" timeout on top of the context's timeout the user provides? Will that solve it?

**Comment by methane** [comment]
> Can you explain this part so I can make adjustments for this issue.

Imagine that network is broken and all packets are losting.

https://github.com/rocketlaunchr/mysql-go/blob/c0e3010b1d0931b07197de0c6ff67c4840b6fae0/conn.go#L139-L157

`kill(c.killerPool, c.connectionID)` will not return forever too because of you don't pass the context.  And `errChan <- ctx.Err()` will be not executed too.

And since `cancelFunc()` is not called forever, `c.conn.PingContext(cancelCtx)` will not return forever too.

> What if I add a "overarching" timeout on top of the context's timeout the user provides? Will that solve it?

At least, you need to add timeout for kill query.

Additionally, you need to wait `c.conn.PingContext`, `c.conn.ExecContext` returns.  Connections shouldn't be used simultaneously.

**Comment by rocketlaunchr-cto** [comment]
I have addressed these issues.
I have added a timeout to `kill` function via a context too.
